apiVersion: apps/v1
kind: Deployment
metadata:
  name: "examples.basic"
  labels:
    basic.label: "false"
spec:
  selector:
    matchLabels:
      override: "examples.basic"
  template:
    metadata:
      labels:
        override: "examples.basic"
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep infinity
        - name: headers
          image: bukowa/http-headers:1.2.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /readinessProbe
          livenessProbe:
            httpGet:
              port: 8080
              path: /livenessProbe