name: Test in cluster

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run examples apply
        run: |
          ./examples-apply.sh
